spring.application.name=sales-api
spring.datasource.url=jdbc:postgresql://localhost:5433/sales
spring.datasource.username=postgres
spring.datasource.password=5467

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
